server:
  port: 7702

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: Lucky@143

# Hibernate Dialect
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


#Spring Security default user and password
#  security:
#    user:
#      name: shashi
#      password: password
#      roles: ADMIN


#JWT
jwt:
  secret: 4dc53f14571acec9adaa29b72614472e1e4ffec50f0ec30a1c910c6b0f1ffa02
  expiry-milliseconds: 14400000